export const SEND_ITEM_SUCCESS = "SEND_ITEM_SUCCESS"
export const SEND_ITEM_START = "SEND_ITEM_START"
export const SEND_ITEM_FAILED = "SEND_ITEM_FAILED"
export const DELETE_ITEM = "DELETE_ITEM"

export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS"
export const GET_HOT_QUESTIONS_SUCCESS = "GET_HOT_QUESTIONS_SUCCESS"
export const GET_QUESTION_SUCCESS = "GET_QUESTION_SUCCESS"
export const ADD_QUESTION_SUCCESS = "ADD_QUESTION_SUCCESS"
export const GET_MY_QUESTIONS_SUCCESS = "GET_MY_QUESTIONS_SUCCESS"

export const ADD_ANSWER_SUCCESS = "ADD_ANSWER_SUCCESS"
export const GET_ANSWERS_SUCCESS = "GET_ANSWERS_SUCCESS"

export const AUTHENTICATE_USER_SUCCESS = "AUTHENTICATE_USER_SUCCESS"
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"